name: flutter_file_downloader_plus
description: A simple flutter plugin that downloads any file type to downloads directory
version: 2.0.1-dev.1
issue_tracker: https://github.com/sherazahmad720/flutter_file_downloader_plus/issues
homepage: https://github.com/sherazahmad720/flutter_file_downloader_plus

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.2.0"
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.1.1

flutter:
  plugin:
    platforms:
      android:
        package: com.sherazi.flutter_file_downloader_plus
        pluginClass: FlutterFileDownloaderPlugin
#      ios:
#        pluginClass: FlutterFilesDownloaderPlugin